# Generated by Django 5.2 on 2025-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadoEleitoralRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.CharField(db_column='SG_PARTIDO', max_length=20)),
                ('candidato', models.CharField(db_column='NM_URNA_CANDIDATO', max_length=200)),
                ('cargo', models.CharField(db_column='DS_CARGO', max_length=100)),
                ('bairro', models.CharField(db_column='NM_BAIRRO', max_length=200)),
                ('votos', models.IntegerField(db_column='QT_VOTOS')),
            ],
            options={
                'verbose_name': 'Dado Eleitoral Raw',
                'db_table': 'sua_tabela_mysql_existente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DadoEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_partido', models.CharField(max_length=20, verbose_name='Sigla do Partido')),
                ('nm_urna_candidato', models.CharField(max_length=200, verbose_name='Nome do Candidato')),
                ('ds_cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('nm_bairro', models.CharField(max_length=200, verbose_name='Nome do Bairro')),
                ('qt_votos', models.IntegerField(default=0, verbose_name='Quantidade de Votos')),
                ('ano_eleicao', models.IntegerField(default=2016, verbose_name='Ano da Eleição')),
                ('nm_municipio', models.CharField(default='RIO DE JANEIRO', max_length=200, verbose_name='Município')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dado Eleitoral',
                'verbose_name_plural': 'Dados Eleitorais',
                'db_table': 'dados_eleitorais',
                'indexes': [models.Index(fields=['sg_partido'], name='dados_eleit_sg_part_79f801_idx'), models.Index(fields=['nm_urna_candidato'], name='dados_eleit_nm_urna_e7f069_idx'), models.Index(fields=['nm_bairro'], name='dados_eleit_nm_bair_04ceec_idx'), models.Index(fields=['sg_partido', 'nm_urna_candidato'], name='dados_eleit_sg_part_560fbd_idx')],
            },
        ),
    ]
