# Generated by Django 5.2.1 on 2025-06-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadoEleitoral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano_eleicao', models.CharField(db_column='ANO_ELEICAO', max_length=4, verbose_name='Ano da Eleição')),
                ('sg_uf', models.CharField(db_column='SG_UF', max_length=2, verbose_name='Código UF')),
                ('nm_ue', models.CharField(db_column='NM_UE', max_length=64, verbose_name='Nome da Unidade Eleitoral')),
                ('ds_cargo', models.CharField(db_column='DS_CARGO', max_length=50, verbose_name='Descrição do Cargo')),
                ('nr_candidato', models.CharField(db_column='NR_CANDIDATO', max_length=8, verbose_name='Número do Candidato')),
                ('nm_candidato', models.CharField(db_column='NM_CANDIDATO', max_length=64, verbose_name='Nome do Candidato')),
                ('nm_urna_candidato', models.CharField(db_column='NM_URNA_CANDIDATO', max_length=64, verbose_name='Nome na Urna')),
                ('nr_cpf_candidato', models.CharField(db_column='NR_CPF_CANDIDATO', max_length=11, verbose_name='CPF do Candidato')),
                ('nr_partido', models.CharField(db_column='NR_PARTIDO', max_length=100, verbose_name='Número do Partido')),
                ('sg_partido', models.CharField(db_column='SG_PARTIDO', max_length=10, verbose_name='Sigla do Partido')),
                ('nr_turno', models.IntegerField(db_column='NR_TURNO', verbose_name='Número do Turno')),
                ('qt_votos', models.DecimalField(db_column='QT_VOTOS', decimal_places=0, max_digits=10, verbose_name='Quantidade de Votos')),
                ('nm_bairro', models.CharField(db_column='NM_BAIRRO', max_length=100, verbose_name='Nome do Bairro')),
                ('nr_latitude', models.CharField(db_column='NR_LATITUDE', max_length=100, verbose_name='Latitude')),
                ('nr_longitude', models.CharField(db_column='NR_LONGITUDE', max_length=100, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Dado Eleitoral',
                'verbose_name_plural': 'Dados Eleitorais',
                'db_table': 'eleicoes_rio',
                'managed': False,
            },
        ),
    ]
